bitcamp-teams/mos

mos/build.gradle, mos/src/main/java/com/mos/domain/code/controller/CodeController.java, mos/src/main/java/com/mos/domain/code/dto/CodeGroupRequestDto.java, mos/src/main/java/com/mos/domain/code/dto/CodeGroupResponseDto.java, mos/src/main/java/com/mos/domain/code/dto/CodeRequestDto.java, mos/src/main/java/com/mos/domain/code/dto/CodeResponseDto.java, mos/src/main/java/com/mos/domain/code/entity/Code.java, mos/src/main/java/com/mos/domain/code/entity/CodeGroup.java, mos/src/main/java/com/mos/domain/code/exception/CodeException.java, mos/src/main/java/com/mos/domain/code/repository/CodeRepository.java, mos/src/main/java/com/mos/domain/code/service/CodeService.java, mos/src/main/java/com/mos/domain/code/service/impl/DefaultCodeService.java, mos/src/main/java/com/mos/global/common/EntityObject.java, mos/src/main/java/com/mos/global/common/message/Result.java, mos/src/main/java/com/mos/global/common/paging/Paging.java, mos/src/main/resources/application.properties, mos/src/main/resources/com/mos/domain/code/repository/CodeRepository.xml
- 공통코드 api
- api 반환객체 (`Result.java`)
- Paging 객체
=> Feat: 공통코드 api

mos/src/main/java/com/mos/domain/githuboauth/config/WebClientConfig.java, mos/src/main/java/com/mos/domain/githuboauth/controller/GithubOAuthController.java, mos/src/main/java/com/mos/domain/githuboauth/controller/HomeController.java, mos/src/main/java/com/mos/domain/githuboauth/controller/MemberController.java, mos/src/main/java/com/mos/domain/githuboauth/dao/MemberDao.java, mos/src/main/java/com/mos/domain/githuboauth/service/GithubOAuthService.java, mos/src/main/java/com/mos/domain/githuboauth/service/MBMemberService.java, mos/src/main/java/com/mos/domain/githuboauth/service/MemberService.java, mos/src/main/java/com/mos/domain/githuboauth/vo/Member.java, mos/src/main/java/com/mos/domain/githuboauth/vo/MemberJoinDto.java
=> Feat: github login

mos/src/main/java/com/mos/domain/member/controller/GithubOAuthController.java, mos/src/main/java/com/mos/domain/member/service/MemberService.java, mos/src/main/java/com/mos/domain/member/service/impl/GithubOAuthService.java, mos/src/main/resources/application.properties
=> github login refactoring

mos/src/main/java/com/mos/domain/study/repository/StudyRepository.java, mos/src/main/java/com/mos/domain/study/service/StudyService.java, mos/src/main/java/com/mos/domain/study/service/impl/DefaultStudyService.java, mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java, mos/src/main/java/com/mos/domain/wiki/dto/WikiDto.java, mos/src/main/java/com/mos/domain/wiki/repository/WikiRepository.java, mos/src/main/java/com/mos/domain/wiki/service/WikiService.java, mos/src/main/java/com/mos/domain/wiki/service/impl/DefaultWikiService.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/study/list.html, mos/src/main/resources/templates/study/view.html
스터디 모집글을 모집번호에 따라 삭제하는 기능 추가
조건을 만족하는 경우에만 삭제 가능하도록 기능 추가,
HTTP DELETE 메서드 사용하도록 변경 (현재 GET)
로그인한 유저가 스터디장(작성자)인 경우 
AND 
해당 스터디에 회원이 스터디장뿐인 경우
=> Feat(스터디 모집): 삭제 기능구현

mos/src/main/resources/templates/index.html
=> Fix: thymeleaf url 수정

mos/src/main/resources/application.properties
=> kakao properties modify

mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/java/com/mos/domain/study/repository/StudyRepository.java, mos/src/main/java/com/mos/domain/study/service/StudyService.java, mos/src/main/java/com/mos/domain/study/service/impl/DefaultStudyService.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/templates/study/edit.html, mos/src/main/resources/templates/study/view.html
=> Feat(Study): 스터디 모집글 edit 기능 구현

mos/src/main/resources/templates/study/edit.html
=> fix(study): 스터디 편집 템플릿 오류 수정

mos/src/main/java/com/mos/global/auth/controller/GithubOAuthController.java, mos/src/main/java/com/mos/global/auth/service/GithubOAuthService.java, mos/src/main/java/com/mos/global/auth/service/GoogleOAuthService.java, mos/src/main/java/com/mos/global/auth/service/KakaoService.java, mos/src/main/java/com/mos/global/auth/service/OAuthService.java
각 OAuht Service 생성자들 수정했고, request 보내는 메소드에 request 보내면서 parsing 하는 코드 추가했습니다.
=> OAuth refactoring

mos/src/main/java/com/mos/global/auth/controller/OAuthController.java, mos/src/main/java/com/mos/global/auth/handler/request/GithubLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/request/GoogleLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/request/KakaoLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/response/GithubLoginResponseHandler.java, mos/src/main/java/com/mos/global/auth/handler/response/GoogleLoginResponseHandler.java, mos/src/main/java/com/mos/global/auth/handler/response/KakaoLoginResponseHandler.java, mos/src/main/java/com/mos/global/auth/handler/response/LoginResponseHandler.java, mos/src/main/resources/templates/header.html
- localStorage 에 엑세스 토큰 보관
- OAuth 로그아웃 api 호출 시 localStorage 에서 꺼내서 로그아웃 컨트롤러에 전달 
- 브라우저 닫기 이벤트 때 localStorage 에서 토큰 삭제
=> Feat: 로그아웃 시 토큰만료를 위해 localStorage 에 보관

mos/src/main/java/com/mos/HomeController.java, mos/src/main/java/com/mos/IndexController.java, mos/src/main/java/com/mos/domain/member/controller/MemberController.java, mos/src/main/java/com/mos/domain/member/dto/MemberDto.java, mos/src/main/java/com/mos/global/auth/LoginUser.java, mos/src/main/java/com/mos/global/auth/config/LoginUserArgumentResolver.java, mos/src/main/java/com/mos/global/auth/controller/OAuthController.java, mos/src/main/java/com/mos/global/auth/dto/SessionUser.java, mos/src/main/java/com/mos/global/auth/handler/LoginApiProvider.java, mos/src/main/java/com/mos/global/auth/handler/request/GithubLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/request/GoogleLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/request/KakaoLoginRequestHandler.java, mos/src/main/java/com/mos/global/auth/handler/response/LoginResponseHandler.java, mos/src/main/java/com/mos/global/config/WebConfig.java, mos/src/main/resources/com/mos/domain/member/repository/MemberRepository.xml, mos/src/main/resources/templates/auth/form.html, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/index.html
- SSR 로 우선 구현함. --> 회원가입 폼 modal 로 수정해야됨
=> Refactor: login - signup 구현

mos/build.gradle, mos/src/main/java/com/mos/domain/member/controller/MemberApiController.java, mos/src/main/java/com/mos/domain/member/dto/MemberDto.java, mos/src/main/java/com/mos/domain/member/dto/MemberJoinDto.java, mos/src/main/java/com/mos/global/auth/handler/RequestAttributes.java, mos/src/main/java/com/mos/global/common/ErrorCode.java, mos/src/main/java/com/mos/global/common/exception/ApiControllerAdvice.java, mos/src/main/java/com/mos/global/common/message/Result.java, mos/src/main/java/com/mos/global/config/SpringContext.java, mos/src/main/resources/com/mos/domain/member/repository/MemberRepository.xml, mos/src/main/resources/templates/auth/form.html, mos/src/main/resources/templates/header.html
- member api 추가
- Api advice 추가
- 에러코드 enum 추가
- validation 추가
- 스프링에 의존하지 않는 클래스에서 bean 을 가져오기 위한 ApplicationContextAware 추가
=> Feat: api 관련 작업

mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/resources/templates/footer.html, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/study/edit.html, mos/src/main/resources/templates/study/form.html, mos/src/main/resources/templates/study/view.html, mos/src/main/resources/templates/wiki/editWiki.html, mos/src/main/resources/templates/wiki/form.html, mos/src/main/resources/templates/wiki/viewWiki.html
스터디 및 위키의 작성/조회/편집에 toast-ui editor 를 적용했습니다.
=> Feat(Study,Wiki): toast-ui editor 적용

mos/src/main/java/com/mos/domain/member/controller/MemberApiController.java, mos/src/main/java/com/mos/domain/member/dto/MemberJoinDto.java, mos/src/main/java/com/mos/global/auth/controller/OAuthController.java, mos/src/main/resources/com/mos/domain/member/repository/MemberRepository.xml, mos/src/main/resources/static/js/auth/modal.js, mos/src/main/resources/templates/header.html
- 기존회원 : db 값 "loginUser" 세션에 저장
- 신규회원 : OAuth 로그인 후 회원 가입 시점에 세션에 저장
=> Fix: 회원 가입 후 세션 불일치 수정

mos/build.gradle, mos/src/main/java/com/mos/IndexController.java, mos/src/main/java/com/mos/domain/member/controller/MemberApiController.java, mos/src/main/java/com/mos/domain/member/service/impl/DefaultMemberService.java, mos/src/main/java/com/mos/domain/notify/controller/NotifyController.java, mos/src/main/java/com/mos/domain/subscribe/controller/SubscribeController.java, mos/src/main/java/com/mos/domain/subscribe/repository/EmitterRepository.java, mos/src/main/java/com/mos/domain/subscribe/service/SubscribeService.java, mos/src/main/java/com/mos/global/auth/repository/MosSessionRepository.java, mos/src/main/java/com/mos/global/auth/service/SessionService.java, mos/src/main/java/com/mos/global/config/RedisConfig.java, mos/src/main/resources/com/mos/global/auth/repository/MosSessionRepository.xml, mos/src/main/resources/static/js/auth/modal.js, mos/src/main/resources/static/js/subscribe.js, mos/src/main/resources/templates/header.html
- 마지막 활동 30분 이내인 유저 모두 표시
- 로그인 하지 않고 접속한 유저도 표시됨
=> Feat: 현재 접속중인 유저 수 표시

mos/src/main/resources/static/js/auth/modal.js, mos/src/main/resources/templates/header.html
- 로그인 아이콘 뜨기 전에 빈 모달 뜨는 현상 수정
- 모달 애니메이션
=> Style: 로그인 모달 오픈 시 동기호출로 수정

mos/src/main/java/com/mos/IndexController.java, mos/src/main/java/com/mos/domain/notify/controller/NotifyController.java, mos/src/main/java/com/mos/domain/notify/dto/NotificationDto.java, mos/src/main/java/com/mos/global/auth/controller/OAuthController.java, mos/src/main/java/com/mos/global/notification/dto/NotificationsResponseDto.java, mos/src/main/java/com/mos/global/notification/repository/NotificationRepository.java, mos/src/main/java/com/mos/global/notification/service/NotificationService.java, mos/src/main/resources/com/mos/global/notification/repository/NotificationRepository.xml, mos/src/main/resources/static/css/auth/modal.css, mos/src/main/resources/static/js/notification/notification.js, mos/src/main/resources/static/js/subscribe.js, mos/src/main/resources/templates/header.html
- header 에 있던 알림 관련 js 분리
- 알림 아이콘 수정 및 알림 갯수 표시
TODO : 알림 경과시간 표시 및 알림 애니메이션 추가
=> Feat: 알림 아이콘 수정

mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java, mos/src/main/resources/templates/study/view.html
=> Fix(study, wiki): wiki/view에서 wikiNo 파라미터 없는 경우 대응

mos/src/main/resources/com/mos/domain/member/repository/MemberRepository.xml, mos/src/main/resources/com/mos/domain/wiki/repository/WikiRepository.xml, mos/src/main/resources/templates/wiki/modoowikilist.html
=> Fix(DB): table 변경 (curriculum => wiki)

mos/build.gradle, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/static/js/study/view.js, mos/src/main/resources/static/js/wiki/wikitree-edit.js, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/study/view.html, mos/src/main/resources/templates/wiki/view.html
=> Design(Wiki): Layout

mos/src/main/resources/templates/index.html, mos/src/main/resources/templates/study/view.html
=> Fix(index): index redirect 제거

mos/build.gradle, mos/src/main/java/com/mos/IndexController.java, mos/src/main/java/com/mos/domain/code/repository/CodeRepository.java, mos/src/main/java/com/mos/domain/code/service/CodeService.java, mos/src/main/java/com/mos/domain/code/service/impl/DefaultCodeService.java, mos/src/main/java/com/mos/global/auth/service/SessionService.java, mos/src/main/java/com/mos/global/config/db/DataSourceAspect.java, mos/src/main/java/com/mos/global/config/db/DataSourceConfig.java, mos/src/main/java/com/mos/global/config/db/DataSourceType.java, mos/src/main/java/com/mos/global/config/db/RoutingDataSource.java, mos/src/main/java/com/mos/global/config/db/RoutingDataSourceManager.java, mos/src/main/resources/com/mos/domain/code/repository/CodeRepository.xml, mos/src/main/resources/static/css/styles.css, mos/src/main/resources/templates/index.html, mos/src/main/resources/templates/member/editProfile.html, mos/src/main/resources/templates/member/myWriteCommentList.html, mos/src/test/java/com/mos/domain/code/service/impl/DefaultCodeServiceTest.java, mos/src/test/java/com/mos/global/config/db/DataSourceConfigTest.java, mos/src/test/java/com/mos/global/config/db/RoutingDataSourceConfigTest.java
`@Transactional(readOnly = true)` 로 select 시 slave db 에 쿼리, 나머지(insert / update / delete)  쿼리는 master db 로 쿼리됨.
=> Feat: DB 이중화 구현

mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/static/js/wiki/hide-header.js, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/wiki/view.html
- 스크롤 업/다운에 따라 헤더를 숨기거나 보여줍니다.
'위키에서만' 헤더에 컨텐츠가 가려지는 문제가 있어서 적용했어요.
=> Design(wiki): 스크롤 반응형 헤더

mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/java/com/mos/domain/study/dto/StudyAddDto.java, mos/src/main/resources/templates/study/form.html
스터디 모집 글에서 Bean validation 적용해서 빈 칸 입력 시 error 텍스트 출력하게 수정
어떤 변경 사항이 있나요?
- [V] 새로운 기능 추가
- [V] 코드 리팩토링
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.  [Commit message convention](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/) 참고
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> 281 feat study form bean validation

mos/src/main/java/com/mos/domain/comment/controller/CommentApiController.java, mos/src/main/java/com/mos/domain/comment/repository/CommentApiRepository.java, mos/src/main/java/com/mos/domain/comment/service/CommentApiService.java, mos/src/main/java/com/mos/domain/comment/service/impl/DefaultCommentApiService.java, mos/src/main/resources/com/mos/domain/comment/repository/CommentApiRepository.xml, mos/src/main/resources/static/css/header.css, mos/src/main/resources/static/css/styles.css, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/static/js/comment/asyncComment.js, mos/src/main/resources/static/js/hide-header.js, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/wiki/view.html
- Fix(Header) 헤더 Position 변경 문제 해결 및 스크롤 반응형 헤더 전역으로 적용
위키 댓글에 수정/추가/대댓글 기능 추가했어요.
어떤 변경 사항이 있나요?
=> Feat(comment):대댓글/수정/삭제 기능 추가

mos/build.gradle, mos/src/main/java/com/mos/domain/wiki/controller/WikiApiController.java, mos/src/main/java/com/mos/domain/wiki/dto/WikiDto.java, mos/src/main/java/com/mos/domain/wiki/repository/WikiApiRepository.java, mos/src/main/java/com/mos/domain/wiki/service/WikiApiService.java, mos/src/main/java/com/mos/domain/wiki/service/impl/DefaultWikiApiService.java, mos/src/main/resources/com/mos/domain/wiki/repository/WikiApiRepository.xml, mos/src/main/resources/static/js/api/wiki/wiki.js, mos/src/main/resources/static/js/index.js, mos/src/main/resources/templates/index.html
인덱스 페이지에 위키 카드리스트로 수정했습니다. 
-> 추후 스터디 모집 카드 리스트로 변경
어떤 변경 사항이 있나요?
=> Refactor(index): index 페이지 카드 ui

mos/src/main/java/com/mos/domain/study/dto/StudyDto.java
사용하지 않는 import 제거
어떤 변경 사항이 있나요?
=> Fix: import 정리

mos/build.gradle
jdbc session 저장소 다시 되돌렸습니다..
어떤 변경 사항이 있나요?
=> refactor: jdbc session 되돌림

mos/src/main/java/com/mos/domain/comment/service/impl/DefaultCommentApiService.java, mos/src/main/resources/com/mos/domain/comment/repository/CommentApiRepository.xml, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/static/js/comment/asyncComment.js, mos/src/main/resources/static/js/wiki/wikitree-edit.js, mos/src/main/resources/templates/wiki/view.html
Comment의 Reply 기능 오류 수정
어떤 변경 사항이 있나요?
=> 279 featcomment editdeletereply

mos/src/main/resources/static/js/comment/asyncComment.js
- 본인 아닌 경우 대댓글 버튼이 안나오던 문제 수정
Fix(comment, wiki)
- 본인 아닌 경우 대댓글 버튼이 안나오던 문제 수정
어떤 변경 사항이 있나요?
=> Fix(comment, wiki)

mos/src/main/resources/static/js/auth/login.js
새로고침, 페이지 이동 시 로그인 풀림 수정
어떤 변경 사항이 있나요?
=> fix: 로그인 풀림

mos/src/main/resources/templates/member/mystudy.html
myStudy CSS 수정
스터디원 -> sweetAlert 적용
스터디장 -> 신청 메시지 정렬, 신청 없을 시 sweetAlert 창 적용
어떤 변경 사항이 있나요?
- [V] CSS 등 사용자 UI 디자인 변경
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.  [Commit message convention](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/) 참고
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> mystudy css 수정

mos/src/main/resources/templates/study/edit.html
study/edit의 toast ui image upload 적용
어떤 변경 사항이 있나요?
- [v] 새로운 기능 추가
- [v] 커밋 메시지 컨벤션에 맞게 작성했습니다.  [Commit message convention](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/) 참고
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
=> study/edit의 toast ui image upload 적용

mos/src/main/resources/templates/study/edit.html
=> study/edit 수정

mos/src/main/resources/static/js/wiki/wikitree-edit.js, mos/src/main/resources/static/js/wiki/wikitree-view.js
=> Fix(Wiki): Editmode 에서 위키 없는 경우 대응

mos/src/main/resources/static/css/wiki/edit.css, mos/src/main/resources/static/js/wiki/wikitree-edit.js
=> Fix(Wiki): Editmode 에서 자식 없는 노드 삭제시 오류 수정

mos/src/main/resources/templates/header.html
=> Fix(wiki/study): 카드 ui 레이아웃 바뀌는 현상 수정, 무한스크롤 계산 수정

mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/java/com/mos/domain/study/dto/StudyUpdateDto.java, mos/src/main/resources/templates/study/edit.html
study/update 메소드에 Bean Validation 적용, BIndResult 추가
edit.html에 에러 메시지 추가
어떤 변경 사항이 있나요?
=> studycontroller update bean validation

mos/src/main/resources/templates/header.html
=> Refactor(study): header nav 링크 정리

mos/src/main/resources/static/css/styles.css, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/index.html
=> Style(main): sticky 적용 중

mos/src/main/resources/static/css/footer.css, mos/src/main/resources/static/css/header.css, mos/src/main/resources/static/css/styles.css, mos/src/main/resources/templates/header.html
=> Design:헤더, 푸터 배경색 변경

mos/src/main/java/com/mos/domain/wiki/controller/WikiApiController.java, mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java, mos/src/main/java/com/mos/domain/wiki/dto/WikiDto.java, mos/src/main/resources/com/mos/domain/wiki/repository/WikiApiRepository.xml, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/static/js/wiki/wikitree-view.js, mos/src/main/resources/templates/wiki/view.html
=> Feat(wiki/view): 작성자 프로필이미지 / 작성일 보여주기

mos/src/main/resources/static/js/study/wikitree-view.js, mos/src/main/resources/templates/study/view.html
=> Fix(study/view): 변수 중복선언 해결

mos/src/main/resources/static/css/styles.css, mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/templates/index.html
=> Style(main): 반응형

mos/src/main/resources/static/css/header.css, mos/src/main/resources/static/css/styles.css
=> Style(main): 헤더, 카드 겹침 수정

mos/src/main/java/com/mos/domain/study/controller/StudyApiController.java, mos/src/main/java/com/mos/domain/study/repository/StudyRepository.java, mos/src/main/java/com/mos/domain/study/service/StudyService.java, mos/src/main/java/com/mos/domain/study/service/impl/DefaultStudyService.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/static/js/api/study/study.js, mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/templates/auth/login.html, mos/src/main/resources/templates/index.html
=> Feat(main/study): 검색 기능 추가

mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/templates/index.html
=> Fix(main): 스크롤 시 검색어 유지

mos/src/main/java/com/mos/domain/study/repository/StudyRepository.java, mos/src/main/java/com/mos/domain/study/service/impl/DefaultStudyService.java, mos/src/main/java/com/mos/domain/wiki/controller/WikiApiController.java, mos/src/main/java/com/mos/domain/wiki/repository/WikiApiRepository.java, mos/src/main/java/com/mos/domain/wiki/service/WikiApiService.java, mos/src/main/java/com/mos/domain/wiki/service/impl/DefaultWikiApiService.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/com/mos/domain/wiki/repository/WikiApiRepository.xml, mos/src/main/resources/static/css/styles.css, mos/src/main/resources/static/js/api/wiki/wiki.js, mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/static/js/wiki/index.js, mos/src/main/resources/templates/index.html, mos/src/main/resources/templates/wiki/modooWikiList.html
검색 키워드에 따른 갯수 표시
어떤 변경 사항이 있나요?
=> Refactor: 검색 키워드에 따른 갯수 표시

mos/src/main/java/com/mos/domain/study/dto/StudyDto.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/static/js/wiki/index.js
메인/위키 카드에 프로필 이미지 표시
어떤 변경 사항이 있나요?
=> Feat: 카드에 프로필 이미지 표시

mos/src/main/java/com/mos/domain/member/repository/MemberRepository.java, mos/src/main/java/com/mos/domain/member/service/MemberService.java, mos/src/main/java/com/mos/domain/member/service/impl/DefaultMemberService.java, mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java, mos/src/main/resources/com/mos/domain/member/repository/MemberRepository.xml, mos/src/main/resources/static/css/study/view.css, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/templates/study/edit.html, mos/src/main/resources/templates/wiki/edit.html, mos/src/main/resources/templates/wiki/view.html
스터디, 위키 수정은 스터디장, 스터디원만 가능하게 변경
=> Auth(study/wiki): authorization study/wiki

mos/src/main/resources/static/css/study/view.css, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/templates/header.html, mos/src/main/resources/templates/wiki/view.html
=> Design(wiki/study): view

mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java, mos/src/main/java/com/mos/domain/wiki/dto/WikiDto.java, mos/src/main/resources/com/mos/domain/study/repository/StudyRepository.xml, mos/src/main/resources/com/mos/domain/wiki/repository/WikiApiRepository.xml, mos/src/main/resources/static/js/study/index.js, mos/src/main/resources/static/js/util/url-validator.js, mos/src/main/resources/static/js/wiki/index.js, mos/src/main/resources/templates/index.html, mos/src/main/resources/templates/wiki/modooWikiList.html
추가: 이미지 없는 경우 랜덤하게 보이도록 변경(단순히 요청 URL을 쪼갠 것)
=> Feat(wiki): 모두의 위키 카드UI => 첫번째 이미지를 썸네일에서 보이도록 변경

mos/src/main/resources/static/js/study/index.js
변수명 문제 (content => introduction)
=> Fix(Study):카드 UI 사진 로딩 오류 수정

mos/src/main/resources/templates/study/view.html
=> Fix(Study):Comment js 스크립트 추가

mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/templates/study/view.html
=> Design 패딩 추가

mos/src/main/java/com/mos/domain/study/controller/StudyController.java, mos/src/main/java/com/mos/domain/wiki/controller/WikiController.java
=> Fix(Auth): 스터디 권한체크 예외처리

mos/src/main/resources/static/css/study/view.css, mos/src/main/resources/static/css/wiki/edit.css, mos/src/main/resources/static/css/wiki/view.css, mos/src/main/resources/templates/study/view.html, mos/src/main/resources/templates/wiki/edit.html, mos/src/main/resources/templates/wiki/view.html
=> Design(view)

mos/src/main/resources/static/js/study/view.js, mos/src/main/resources/templates/study/view.html, mos/src/main/resources/templates/wiki/view.html
- 로그인 한 경우에만 신청 가능
- 이미 가입된 경우는 버튼 보이지 않음
=> Fix(study apply)

mos/src/main/resources/static/css/auth/modal.css, mos/src/main/resources/static/js/comment/study-async-comment.js, mos/src/main/resources/static/js/subscribe.js, mos/src/main/resources/templates/study/view.html
스터디 모집글 댓글 알람 안오던 문제 수정
어떤 변경 사항이 있나요?
=> Fix(sse): 실시간 알람 수정

mos/src/main/resources/static/js/subscribe.js
=> Fix: sse 중복연결 수정

mos/src/main/resources/templates/member/mystudy.html
- 마이스터디에서 스터디 타이틀 클릭시 해당 스터디 모집글로 이동하도록 변경 (이전: 위키)
=> Fix(member/mypage): 스터디 클릭시 링크주소 변경

mos/src/main/resources/static/css/study/view.css
스터디 편집/삭제 버튼 두는 .study-edit에 padding 추가
=> Design(edit buttons)
